"""update content entity fields

Revision ID: 936232b3970a
Revises: 20260304_215402
Create Date: 2026-03-24 16:35:46.370941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '936232b3970a'
down_revision = '20260304_215402'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('status', sa.String(length=20), nullable=False, server_default='unknown'))
    op.add_column('characters', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('race_id', sa.Integer(), nullable=True))
    op.alter_column('characters', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_foreign_key(None, 'characters', 'races', ['race_id'], ['id'], ondelete='SET NULL')
    op.alter_column('entity_relationships', 'relationship_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.add_column('events', sa.Column('event_date', sa.String(length=100), nullable=False))
    op.add_column('events', sa.Column('event_date_end', sa.String(length=100), nullable=True))
    op.alter_column('events', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('events', 'date')
    op.alter_column('locations', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('races', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('races', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('locations', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('events', sa.Column('date', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.alter_column('events', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('events', 'event_date_end')
    op.drop_column('events', 'event_date')
    op.alter_column('entity_relationships', 'relationship_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.alter_column('characters', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('characters', 'race_id')
    op.drop_column('characters', 'age')
    op.drop_column('characters', 'status')
    # ### end Alembic commands ###
